force-app/main/default/objects/recordCDC__e/recordCDC__e.object-meta.xml
<CustomObject>
    <description>Change data capture events generated by the Salesforce platform.</description>
    <label>recordCDC</label>
    <pluralLabel>recordCDC</pluralLabel>
</CustomObject>

force-app/main/default/objects/recordCDC__e/fields/recordID__c.field-meta.xml
<CustomField>
    <fullName>recordID__c</fullName>
    <description>ID of the record that changed.</description>
    <label>recordID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/recordCDC__e/fields/serial_no__c.field-meta.xml
<CustomField>
    <fullName>serial_no__c</fullName>
    <description>Serial number of the solar panel track associated with the CDC event.</description>
    <label>serial no</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/recordCDCTriggerTest.cls
/**
* This class contains unit tests for validating the behavior of Apex classes
* and triggers.
*
* Unit tests are class methods that verify whether a particular piece
* of code is working properly. Unit test methods take no arguments,
* commit no data to the database, and are flagged with the testMethod
* keyword in the method definition.
*
* All test methods in an org are executed whenever Apex code is deployed
* to a production org to confirm correctness, ensure code
* coverage, and prevent regressions. All Apex classes are
* required to have at least 75% code coverage in order to be deployed
* to a production org. In addition, all triggers must have some code coverage.
* 
* The @isTest class annotation indicates this class only contains test
* methods. Classes defined with the @isTest annotation do not count against
* the org size limit for all Apex scripts.
*
* See the Apex Language Reference for more information about Testing and Code Coverage.
*/
@IsTest
public class recordCDCTriggerTest {
    
    @IsTest
    static void recordCDCTriggerTest() {
        recordCDC__e evt = new recordCDC__e(
            serial_no__c = 'SN1234',
            recordID__c = 'Some value');
        
        Test.startTest();
        Database.SaveResult sr = EventBus.publish(evt);
        Test.stopTest();
        
        System.assertEquals(true, sr.isSuccess());
        
    }
    
}